# Generated by Django 4.2 on 2025-07-03 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mlb_id', models.IntegerField(unique=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('full_name', models.CharField(max_length=100)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('birth_city', models.CharField(blank=True, max_length=100)),
                ('birth_state_province', models.CharField(blank=True, max_length=50)),
                ('birth_country', models.CharField(blank=True, max_length=50)),
                ('height', models.CharField(blank=True, max_length=10)),
                ('weight', models.IntegerField(blank=True, null=True)),
                ('primary_position', models.CharField(blank=True, choices=[('P', 'Pitcher'), ('C', 'Catcher'), ('1B', 'First Base'), ('2B', 'Second Base'), ('3B', 'Third Base'), ('SS', 'Shortstop'), ('LF', 'Left Field'), ('CF', 'Center Field'), ('RF', 'Right Field'), ('OF', 'Outfield'), ('IF', 'Infield'), ('DH', 'Designated Hitter'), ('UT', 'Utility')], max_length=3)),
                ('bat_side', models.CharField(blank=True, choices=[('L', 'Left'), ('R', 'Right'), ('S', 'Switch')], max_length=1)),
                ('pitch_hand', models.CharField(blank=True, choices=[('L', 'Left'), ('R', 'Right')], max_length=1)),
                ('mlb_debut_date', models.DateField(blank=True, null=True)),
                ('final_game_date', models.DateField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_players', to='teams.team')),
            ],
            options={
                'db_table': 'players',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='PlayerTeamHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('transaction_type', models.CharField(blank=True, choices=[('draft', 'Draft'), ('trade', 'Trade'), ('free_agent', 'Free Agent'), ('waiver', 'Waiver Claim'), ('purchase', 'Purchase'), ('call_up', 'Call Up'), ('option', 'Option'), ('dfa', 'Designated for Assignment'), ('release', 'Release'), ('retirement', 'Retirement')], max_length=20)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_history', to='players.player')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_history', to='teams.team')),
            ],
            options={
                'db_table': 'player_team_history',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='PlayerSeason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.IntegerField()),
                ('games_played', models.IntegerField(default=0)),
                ('games_started', models.IntegerField(default=0)),
                ('at_bats', models.IntegerField(default=0)),
                ('runs', models.IntegerField(default=0)),
                ('hits', models.IntegerField(default=0)),
                ('doubles', models.IntegerField(default=0)),
                ('triples', models.IntegerField(default=0)),
                ('home_runs', models.IntegerField(default=0)),
                ('runs_batted_in', models.IntegerField(default=0)),
                ('walks', models.IntegerField(default=0)),
                ('strikeouts', models.IntegerField(default=0)),
                ('stolen_bases', models.IntegerField(default=0)),
                ('caught_stealing', models.IntegerField(default=0)),
                ('batting_average', models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True)),
                ('on_base_percentage', models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True)),
                ('slugging_percentage', models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True)),
                ('ops', models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True)),
                ('fielding_percentage', models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True)),
                ('errors', models.IntegerField(default=0)),
                ('putouts', models.IntegerField(default=0)),
                ('assists', models.IntegerField(default=0)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seasons', to='players.player')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_seasons', to='teams.team')),
            ],
            options={
                'db_table': 'player_seasons',
                'ordering': ['-season', 'player__last_name', 'player__first_name'],
                'unique_together': {('player', 'team', 'season')},
            },
        ),
        migrations.CreateModel(
            name='PlayerAward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('award_name', models.CharField(max_length=100)),
                ('season', models.IntegerField()),
                ('award_type', models.CharField(blank=True, max_length=50)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awards', to='players.player')),
            ],
            options={
                'db_table': 'player_awards',
                'ordering': ['-season', 'award_name'],
                'unique_together': {('player', 'award_name', 'season')},
            },
        ),
        migrations.CreateModel(
            name='PitcherSeason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.IntegerField()),
                ('games_played', models.IntegerField(default=0)),
                ('games_started', models.IntegerField(default=0)),
                ('complete_games', models.IntegerField(default=0)),
                ('shutouts', models.IntegerField(default=0)),
                ('wins', models.IntegerField(default=0)),
                ('losses', models.IntegerField(default=0)),
                ('saves', models.IntegerField(default=0)),
                ('holds', models.IntegerField(default=0)),
                ('blown_saves', models.IntegerField(default=0)),
                ('save_opportunities', models.IntegerField(default=0)),
                ('innings_pitched', models.DecimalField(decimal_places=1, default=0, max_digits=6)),
                ('hits_allowed', models.IntegerField(default=0)),
                ('runs_allowed', models.IntegerField(default=0)),
                ('earned_runs', models.IntegerField(default=0)),
                ('walks_allowed', models.IntegerField(default=0)),
                ('strikeouts', models.IntegerField(default=0)),
                ('home_runs_allowed', models.IntegerField(default=0)),
                ('earned_run_average', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('whip', models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True)),
                ('strikeouts_per_nine', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('walks_per_nine', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pitcher_seasons', to='players.player')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pitcher_seasons', to='teams.team')),
            ],
            options={
                'db_table': 'pitcher_seasons',
                'ordering': ['-season', 'player__last_name', 'player__first_name'],
                'unique_together': {('player', 'team', 'season')},
            },
        ),
    ]
